### ISSUE TITLE
Triggering via keybinding throws error

### ISSUE THREAD

**Issue by batjko** [jseto/plain-2-jasmine#1]
Hey there.

I like everything that keeps me from writing repetitive code, so :+1: !

However, when I write my plain specs as shown in your gif, then highlight all lines and press `Ctrl-Shift-J`, I get this error:

```
Line Number Based runner not available for JavaScript.
If it should exist, add an issue on GitHub, or send your own pull request.
```

I'm not sure what that means, since all I did was highlighting the lines I wanted to transform and then pressed the key binding.

Do I actually _have_ to use the right-click menu every time (which works fine)?

**Comment by jseto** [comment]
What's your OS and Atom version?

**Comment by batjko** [comment]
Sorry, should have mentioned:

Ubuntu 15, 64bit, Atom 1.0.2.

**Comment by jseto** [comment]
I'm using Ubutu 14.04 64bit and Atom 1.0.2

Don't think the issue comes from Ubuntu version. Have you checked if you have other installed package using the same key mapping?

**Comment by batjko** [comment]
I just tried it on a different machine (Windows) and it seems to work there.
I'll check the keybinding resolver on the Ubuntu one and get back to you.

**Comment by jseto** [comment]
I cannot find why it is not working in your system

**Comment by batjko** [comment]
I think it was messed with by some other package, probably the Script runner.
Closing this off.
