### ISSUE TITLE
[Feature Request] Support for Coffeescript files

### ISSUE THREAD

**Issue by batjko** [jseto/plain-2-jasmine#2]
Given my preference for less code, do you think you could support a coffeescript version of this?

That would be swell!

**Comment by jseto** [comment]
I don't write Coffeescript but as far as I know Coffeescript should compile plain JavaScipt as well. 
Maybe I don't fully understand your feature request or I'm wrong.

**Comment by batjko** [comment]
You can't just write Javascript in Coffeescript files (although there is a way), but translating your example into coffee is fairly simple.
It's just a different way of writing the same JS code, and then a transpiler turns it into Javascript before it gets used.

Here's an example:

``` coffeescript
describe 'My awesome package', ->

  describe 'when select Plain to Jasmine from context menu', ->
    it 'should insert Jasmine syntax in selected text', ->
      console.log 'Yay'
      true

  describe 'when select Plain to Jasmine from package menu', ->
    it 'should insert Jasmine syntax in selected text', ->
      console.log 'Doh'
      false

  describe 'when ctrl-shift-j pressed', ->
    it 'should insert Jasmine syntax in selected text', ->
      console.log 'Yea, baby!'
      true
```

Indentation is important.

**Comment by batjko** [comment]
Went ahead and added a PR for you to review.
Turning it into Coffeescript is a lot simpler, and all the tests pass etc.

**Comment by jseto** [comment]
Thank you. Next, TypeScript :smile:

**Comment by batjko** [comment]
woot :+1:
