### ISSUE TITLE
Text not wrapped in Jasmine correctly

### ISSUE THREAD

**Issue by DaftMule** [jseto/plain-2-jasmine#4]
Atom version: 1.1.0
OS: Windows 7 Ultimate
palin-2-jasmine: 0.2.0

I have just installed your package and in trying it out, he plain text is not being wrapped in jasmine syntax correctly.  If I follow the example you give:

```
This awesome package
  when text is selected
    should wrap Jasmine syntax around it
    should be activated by magic
    should buy me a beer
```

Is wrapped as follows:

```
This awesome package
describe( '', function() {

  when text is selected
describe( '', function() {

    should wrap Jasmine syntax around it
it( '', function() {

    should wrap Jasmine syntax around it
});

    should be activated by magic
it( '', function() {

    should be activated by magic
});

  when text is selected
});

This awesome package
});

    it( 'should buy me a beer', function() {

    });
```

Oddly, the last "should" is being handled correctly.  

I have disabled the 3 other community packages but that does not change the output.

**Comment by jseto** [comment]
I'm sorry but I cannot reproduce the behaviour you describe. Can you send the file producing this behaviour? Can you give me more details about what are you doing?

**Comment by DaftMule** [comment]
Have attached a sample file (added .txt  on the end as it won't let me upload .js files)  

Am I doing anything wrong here?  Basically I downloaded and installed Atom, installed your plugin via the Atom plugin install in Settings , created a new blank .js file, wrote the plain text as per enclosed then highlight it all and did CTRL-SHIFT-J.  

[test.js.txt](https://github.com/jseto/plain-2-jasmine/files/33914/test.js.txt)

**Comment by jseto** [comment]
I have been able to reproduce your bug. It is due to the line endings. Your file is coded as CRLF, Windows way, and produces the described behaviour.

I will fix the bug as soon as possible.

Thank you

**Comment by DaftMule** [comment]
Ok.  Thanks for looking into it.
